# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-28 15:28
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_reward_allowed_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='install_type',
            field=models.CharField(choices=[(b'o', b'Organic'), (b'r', b'Referral')], default=b'o', max_length=32),
        ),
        migrations.AddField(
            model_name='user',
            name='refferal_code',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='refferals',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='user',
            name='reffered_by',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
