# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-28 16:46
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_auto_20171128_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='refferals',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, size=None),
        ),
    ]
