# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-04 08:16
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0006_auto_20171128_1650'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_amount', models.IntegerField()),
                ('base_amount', models.IntegerField()),
                ('security', models.IntegerField()),
                ('status', models.IntegerField(choices=[(1, b'Pending'), (2, b'Complete')])),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='db.Booking')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='refferals',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=None),
        ),
    ]
