# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-04 09:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0007_auto_20171204_0816'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='base_amount',
            new_name='booking_charges',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='security',
            new_name='security_amount',
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.IntegerField(choices=[(1, b'Pending'), (2, b'Under Progress'), (3, b'Failed'), (4, b'Complete')]),
        ),
    ]
