# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-20 06:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0008_auto_20171204_0906'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
