# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-29 07:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0012_user_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.IntegerField(choices=[(0, b'unpaid'), (1, b'upcoming'), (2, b'ongoing'), (3, b'completed'), (4, b'cancelled')], default=0),
        ),
    ]
